### ISSUE TITLE
Улучшение программы

### ISSUE THREAD

**Issue by michael-smirnov** [michael-smirnov/DiffuseCatalisation#1]
# План доработки приложения

На последнем собрании были получены новые требования к программе. Условно их можно разделить на 2 категории:
- Желательные
- Обязательные
## Желательные требования

Данные требования не обязаны быть выполнены все вместе. Достаточно выполнить только некоторые.
- 1. **Вывод нормы решений на слое.**
- 2. **Возможность по требованию пользователя вывести на одном графике с функциями `u1(x)` и `u2(x)` графики, соответствующие их (активатора и ингибитора) начальным условиям.**
- 3. Возможность "листать" графики, переходить на заданный номер слоя.
- 4. **По требованию пользователя вывести таблицу со значениями функций `u1(x)` и `u2(x)` на текущем слое (в момент паузы).**
- 5. _При вводе начальных условий обеспечить проверку, не являются ли они при каких-либо`x` отрицательными. Если являются, вывести предупреждение._
- 6. **Если при некоторых параметрах сетки (разбиении по координате и шагу по времени) решение будет расходиться, вывести предупреждение перед началом счета (т.о. обеспечить вычислительную устойчивость).**
- 7. **Возможность сравнивать предельное решение со стационарным, найденным аналитически.**
## Обязательные требования

Включают в себя построение одного из 4-х следующих сервисов:
1. _Сравнение пары слоев численного решения (по норме, по всем узлам)._
2. _Сравнение двух численных решений, полученных *_на разных сетках*_, для слоев, соответствующих одному `t`._
3. _Сравнение двух численных решений, полученных *_разными схемами*_, для слоев, соответствующих одному `t`._
4. **Сравнение численных решений, полученных одним способом, но с разными начальными условиями**
## Итоги

Итак, нам следует:
- [x] Выбрать несколько желательных требований.
- [x] Реализовать выбранные желательные требования.
- [x] Выбрать одно из 4-х обязательных требований.
- [x] Реализовать выбранное обязательное требование.

**Comment by michael-smirnov** [comment]
Все требования, по моему мнению, не являются сильно трудоемкими. Хотя обязательные немного пообъемнее.
Думаю, что стоит разделить требования между нами по типу "один человек - одно требование".
Но прежде стоит выбрать, что следует делать.

По моему мнению, среди **желательных требований** следует выбрать _1-е_ (как самое безобидное), _2-е_ и _4-е_ (т.к. _Н. Р. Стронгина_ очень хочет их увидеть), _6-е_ и _7-е_.
Среди **обязательных требований** я бы выбрал _4-е_.

Каковы ваши мнения?

**Comment by Destrouer** [comment]
Четверг, 26 марта 2015, 7:23 -07:00 от michael-smirnov notifications@github.com:

> Все требования, по моему мнению, не являются сильно трудоемкими. Хотя обязательные немного пообъемнее.
> Думаю, что стоит разделить требования между нами по типу "один человек - одно требование".
> Но прежде стоит выбрать, что следует делать.
> По моему мнению, среди  желательных требований следует выбрать  1-е (как самое безобидное),  2-е и  4-е (т.к.  Н. Р. Стронгина очень хочет их увидеть),  6-е и  7-е .
> Среди  обязательных требований я бы выбрал  4-е .
> Каковы ваши мнения?
> —
> Reply to this email directly or  view it on GitHub .
> 1-4 реализовать нет ни каких проблем, они были предусмотрены, так сказать. 6,7 не совсем понятно как реализовать.
> Из обязательных 2 и 4 очень близки.

С уважением,
Владимир Винницкий
vovanvinnitski@mail.ru

**Comment by ArtemSkrebkov** [comment]
1-е из обязательных самым простым выглядит, 4-е - я чет не очень представляю как будет выглядеть в программе.
3-е не для нас, мы только одну схему сделали.

**Comment by michael-smirnov** [comment]
@Destrouer 

> 6,7 не совсем понятно как реализовать. 

Тебе непонятно, потому что тебя не было на собрании. Хотя эти 2 требования дадут больший плюс в ее глазах нам, чем остальные. Все-таки предлагаю попытаться их выполнить (не получится - не страшно). Предлагаю 6 отдать мне, а 7-е Артему @ArtemSkrebkov.

> Из обязательных 2 и 4 очень близки

Нет, 2-е заключается в том, что задача одна (параметры дифура), а сетки (разбиения по x и шаг по t) - разные. 4-е же заключается в том, что сетка одна и та же, но различаются н.у.

**Comment by michael-smirnov** [comment]
@ArtemSkrebkov 

> 1-е из обязательных самым простым выглядит

Да, но я предлагаю 4-е, потому что она его нам навязывала на собрании. А выглядеть оно будет так же как 1-е - на другом `zedGrapControl` выводится график разности 2-х слоев, а также в каком-нибудь `label` разница по норме.

> 3-е не для нас, мы только одну схему сделали.

Да, его не рассматриваем.

**Comment by Destrouer** [comment]
6,7 - отлично, потом расскажите)
Как я их понял - останавливаем счёт, меняем параметры, запускаем счёт, сравниваем. Получается нет существенной разницы - в одном случае меняем параметры сетки. в другом меняем параметры НУ.

С уважением,
Владимир Винницкий
vovanvinnitski@mail.ru

**Comment by michael-smirnov** [comment]
@Destrouer 

> 6,7 - отлично, потом расскажите)
> Как я их понял - останавливаем счёт, меняем параметры, запускаем счёт, сравниваем.

Да, я расскажу их тебе завтра :) Но понял ты их неверно, там все гораздо прозаичнее.

**Comment by ArtemSkrebkov** [comment]
@michael-smirnov, ок, только тогда ещё надо где-то начальные условия задавать для второго случая, как-то громоздко будет выглядеть.

**Comment by michael-smirnov** [comment]
@ArtemSkrebkov, Сделать приложение с несколькими вкладками. На первой расположить то, что есть сейчас, а вторую посвятить этому интерфейсу. Лучше это завтра будет обсудить, вживую.

**Comment by michael-smirnov** [comment]
Предлагаю разделить работу между нами следующим способом:
@Destrouer  - возьми на себя выполнение желательных требований 1, 2 и 4. Если останется время, сделай 3.
Считаю, что 6 и 7 должен делать один человек, а основное задание 4 - другой. Поэтому вопрос: @ArtemSkrebkov, какую часть возьмешь себе?

**Comment by ArtemSkrebkov** [comment]
@michael-smirnov 
Возьму 6 и 7 из желательных.

Что по срокам, ко вторнику?

**Comment by michael-smirnov** [comment]
Да, нужно сделать ко вторнику. Оптимально - если все. Если что-то не успеете, не беда. Главное правильно разложиться по нагрузке - во вторник нам нужно не только эту прогу показывать, но и задания из методички, варианты которых я высылал вам через вконтакт в .doc файле. То есть нужно что-то сделать в проге и что-то из методички (другие проги не трогаем пока). Оптимально - все свои задания по этой проге и что-нибудь из методички.

**Comment by michael-smirnov** [comment]
В последнем коммите я постарался как можно безболезнее разделить функциональность основной части программы (которой занимаетесь вы) и сервисом №4. Все свои действия с интерфейсом нужно проводить в соответствующих вкладках - "Одиночный эксперимент" и "Сравнение решений"

**Comment by michael-smirnov** [comment]
Обязательное требование сделано. Как у вас?

**Comment by michael-smirnov** [comment]
@Destrouer, твой обработчик проверки несовпадения гармоник (код, что не дает пользователю поставить одну и туже гармонику больше одного раза в н.у.) написан криво. Я не могу, например, выбрать только нулевую и 20-ю гармоники, приходится явно прописывать 5 гармоник, и ставить нулевые коэффициенты перед всеми, кроме 1-й и последней. Я сделал свой обработчик, который использую во вкладке основного требования. Используй тоже мой обработчик.
