### ISSUE TITLE
Сборка частей программы перед показом

### ISSUE THREAD

**Issue by michael-smirnov** [michael-smirnov/DiffuseCatalisation#4]
Ко вторнику необходимо слить все изменения в master. Скорее всего, при merge будут конфликты. Я, честно говоря, боюсь что-нибудь испортить при слиянии веток. @ArtemSkrebkov, ты имеешь опыт больший, чем я при использовании git. Не мог бы ты к завтра слить ветки в master?

**Comment by ArtemSkrebkov** [comment]
Ок, мою ветку можно вливать, Вова замечания поправит и я подготовлю его ветку для слияния.
